# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Renan Toesqui Magalhaes
title: Staff Security Engineer | Cloud & Application Security | Zero Trust Advocate
email: renan@seclabs.cc
website: https://seclabs.cc

# Social links
# twitter_username: renanTM90
github_username:  renantmagalhaes
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: renantmagalhaes
linkedin_username: renantmagalhaes
# pinterest_username: jekyll
#youtube_username: renantmagalhaes
# googleplus_username: +jekyll

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_profile_image: images/profile2.png
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Renan. Building on a technical foundation in DevSecOps and systems administration, I have transitioned from securing critical banking infrastructure for the Brazilian Payment System (SPB) to driving enterprise security initiatives as a **Staff Engineer**. My trajectory has evolved from hands-on infrastructure management to leading complex, cross-functional technical strategies that bridge the gap between technical security and overarching business objectives.
  
  My current focus is on enabling engineering teams to develop software securely by providing the necessary frameworks and tools, including a proactive <mark>AI security posture</mark> to increase development velocity. I specialize in executing the company vision by leading large-scale projects that align technical security with business goals. Central to my approach is the implementation of <mark>Zero Trust principles</mark>, ensuring that security is a seamless, resilient, and supportive part of the organization's growth. I bridge the gap between deep technical execution and GRC initiatives, such as <mark>ISO27001 and GDPR</mark>, to foster a culture where security accelerates delivery.

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Latest Experiences

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interest in software engineering some of my other hobbies are:
   - Biking
   - Gaming
   - Reading (Mostly graphic novels)
   - [Becoming a Master of Martial Arts](https://68.media.tumblr.com/36ce2037081ed8356d1258f627d515e8/tumblr_o7wk33S5bZ1tqh2yyo1_500.gif)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
