# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Renan Toesqui Magalhães
title: Security Engineer | SysAdmin
email: renan@rtm.codes
website: https://rtm.codes

# Social links
twitter_username: renanTM90
github_username:  renantmagalhaes
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: renantmagalhaes
linkedin_username: renantmagalhaes
# pinterest_username: jekyll
#youtube_username: renantmagalhaes
# googleplus_username: +jekyll

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_profile_image: images/profile2.png
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Renan. With a background in DevSecOps, I have extensive experience in the banking sector, collaborating closely with BACEN (Central Bank of Brazil) and SPB (Brazilian Payment System). My expertise spans both Linux and Windows system administration, and I have taken the lead in project management within this domain.
  
  Currently, I am a Security Engineer with a specialization in architecting secure and robust systems for cloud environments. My role encompasses the <mark>design and implementation of best practices</mark> in cloud engineering, ensuring optimal performance and security. I am well-versed in conducting penetration testing to identify and rectify vulnerabilities, ensuring our cloud infrastructure remains impervious to threats. My commitment to continuous learning and staying updated with the latest in cloud security ensures that the systems I work on are both cutting-edge and secure.

  My past experiences can be found on my [Linkedin](https://linkedin.com/in/renantmagalhaes/) profile. 

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Latest Experiences

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interest in software engineering some of my other hobbies are:
   - Biking
   - Gaming
   - Reading (Mostly graphic novels)
   - [Becoming a Master of Martial Arts](https://68.media.tumblr.com/36ce2037081ed8356d1258f627d515e8/tumblr_o7wk33S5bZ1tqh2yyo1_500.gif)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
