# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Renan Toesqui Magalhães
title: SysAdmin | DevOps Engineer 
email: renantmagalhaes@gmail.com
website: https://renantmagalhaes.net

# Social links
twitter_username: renanTM90
github_username:  renantmagalhaes
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: renantmagalhaes
linkedin_username: renantmagalhaes
# pinterest_username: jekyll
#youtube_username: renantmagalhaes
# googleplus_username: +jekyll

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_profile_image: images/profile2.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Renan ....  I'm a former sysadmin working in a Banking environment with BACEN (Central Bank of Brazil) and SPB (Brazilian payment system), with an active participation in Linux and Windows systems administration and responsible for project management in this area. Now working as DevOps engineer focused in build secure and high distributed systems in cloud.

  I am most skilled in: <mark>Linux Administration</mark>, <mark>Kubernetes</mark> and <mark>AWS</mark>

  You can check my full skills list in my ```[Linkedin](https://linkedin.com/in/renantmagalhaes/)``` profile, just click in the header icon <span style="font-family:helvetica; font-size:2em;">**in**</span> 

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Latest Experiences

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Biking
   - Gaming
   - Manga reading
   - [Becoming a Master of Martial Arts](https://68.media.tumblr.com/36ce2037081ed8356d1258f627d515e8/tumblr_o7wk33S5bZ1tqh2yyo1_500.gif)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
