# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Renan Toesqui Magalhães
title: Sysadmin / DevOps Engineer
email: renantmagalhaes@gmail.com
website: https://renantmagalhaes.net

# Social links
twitter_username: renanTM90
github_username:  renantmagalhaes
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: renantmagalhaes
linkedin_username: renantmagalhaes
# pinterest_username: jekyll
youtube_username: renantmagalhaes
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Renan ....  I'm a former sysadmin working in a Banking environment with BACEN (Central Bank of Brazil) and SPB (Brazilian payment system), with an active participation in Linux and Windows systems administration and responsible for project management in this area. Now working as DevOps engineer looking towards a future where automation and a high availability are core pieces of every system 

  I am most skilled in: <mark>Linux Administration</mark> and <mark>Kubernetes</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
